### ISSUE TITLE
SS4 upgrade?

### ISSUE THREAD

**Issue by hdpero** [micschk/silverstripe-rightsidebar#7]
Is there a plan to update this awesome module to be compatible with SS4?
We've started to update it on [fork ](https://github.com/fractaslabs/silverstripe-rightsidebar), once we're ready we'll send you a PR.

**Comment by micschk** [comment]
Our plan is to update modules when we need to use them in SS4 projects.
We've only just started our first project based on SS4, so a PR is very welcome.

​

**Comment by micschk** [comment]
Thanks for the update @hdpero !
I've tagged a 2.0 release for SS4, closing this ticket.
